version: '3.9'
services:
  server:
    build: ./apps/server
    ports:
      - "5174:5174"
    environment:
      - PORT=5174
  client:
    build: ./apps/client
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      - PORT=5173
      - API_PROXY_TARGET=http://server:5174
