version: '3.9'
services:
  server:
    build: 
       context: .
       dockerfile: apps/server/Dockerfile      
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  client:
    build: 
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      - PORT=5173
      - API_PROXY_TARGET=http://server:5174