version: "3.9"
services:
  uzupis-cat-server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5174
    ports:
      - "5174:5174"

  uzupis-cat-client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    # If using nginx proxy config, this just serves the SPA
    ports:
      - "5173:80"
    depends_on:
      - uzupis-cat-server
